### ISSUE TITLE
Missing module rnn_architectures.seq2seq_model.with_decoder.non_moving_window.accumulated_error

### ISSUE THREAD

**Issue by gjmulder** [HansikaPH/time-series-forecasting#2]
```
$ ./utility_scripts/execution_scripts/m3_demo_experiments.sh
Iteration 1 of m3_demo
Traceback (most recent call last):
  File "./generic_model_trainer_3.py", line 5, in <module>
    from generic_model_tester import testing
  File "/home/mulderg/Work/time-series-forecasting/generic_model_tester.py", line 13, in <module>
    from rnn_architectures.seq2seq_model.with_decoder.non_moving_window.accumulated_error.seq2seq_model_tester import \
ModuleNotFoundError: No module named 'rnn_architectures.seq2seq_model.with_decoder.non_moving_window.accumulated_error'
```

Seem to be missing some code:
```
$ ls -l "`echo "rnn_architectures.seq2seq_model.with_decoder.non_moving_window.accumulated_error" | sed 's/\./*/g'`*"
ls: cannot access 'rnn_architectures*seq2seq_model*with_decoder*non_moving_window*accumulated_error*': No such file or directory
```

**Comment by HansikaPH** [comment]
@gjmulder Thanks for pointing this out. I have updated the generic_model_trainer and generic_model_tester accordingly.

**Comment by gjmulder** [comment]
Looks fixed. Thanks for the quick reply!
